### ISSUE TITLE
RSS feed links are broken

### ISSUE THREAD

**Issue by porglezomp** [Apanatshka/Apanatshka.github.io#1]
Feed links point to `localhost:4000`, see e.g. https://github.com/Apanatshka/Apanatshka.github.io/blob/master/feed.xml#L7

**Comment by Apanatshka** [comment]
Thanks for reporting! I'd heard something got messed up in the RSS feed, but I didn't know the links were broken. I know what went wrong, so I hope it won't happen again (I reused a local build to save time). It should be fixed now
